### ISSUE TITLE
Snippy always returning 0 SNPs and alignment file only containing ---

### ISSUE THREAD

**Issue by abdullah314** [tseemann/snippy#270]
I am using snippy for the first that's why I am not sure it's really an issue or my failure to properly run the program. First I tried to align 48 fasta files containing contigs with the reference genome in fasta format using the following commands:
snippy-multi input.tab --ref Reference.fasta > runme.sh
sh ./runme.sh

It went on creating 48 folders correspond to the 48 samples and everything seemed fine until the end. It failed to run a command because the number of SNPs were zero. 
Then to test I ran the program with only one sample file using the command:
snippy --cpus 16 --outdir mysnps --ref Reference.fasta --se sample1.fasta

This completed without any error but when I  examined the newly created folder I observed that the issue still remains. It shows zero snps and aligment only contains dashes. 
Then I went on created a small Reference.fasta artificially and by adding artificial SNPs created a sample.fasta and repeated the above command. Same result. 

please help.

**Comment by abdullah314** [comment]
from the log file
### bwa mem  -Y -M -R '@RG\tID:mysnps\tSM:mysnps' -t 4 reference/ref.fa /home/lssd/Abdullah/NGS_work/vibrio_cholerae_genome/test3/S.fasta | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp/snippy.24883. --threads 4 -m 2000M | samtools fixmate -m - - | samtools sort -l 0 -T /tmp/snippy.24883. --threads 4 -m 2000M | samtools markdup -T /tmp/snippy.24883. -r -s - - > snps.bam

READ 0 WRITTEN 0 
EXCLUDED 0 EXAMINED 0
PAIRED 0 SINGLE 0
DULPICATE PAIR 0 DUPLICATE SINGLE 0
DUPLICATE TOTAL 0

**Comment by tseemann** [comment]
Can you please paste the contents of `input.tab` ?

**Comment by abdullah314** [comment]
Problem solved by using --cpus 1 --ram 1.

**Comment by Nilad** [comment]
Same issue,

On the same reference, i run snippy with "normal" fastq of 600-700 Mo. All work fine.
But, i have for somes strains the R1 and the R2 fastq file have each the size of 1.5 Go.

I have 32Go of ram on my test desktop.

I try with default ram and cpu usage for it (--cpus 8 --ram 8), without success.
I try with a large ram and cpu usage for it (--cpus 15 --ram 15), without success.
I try with --cpus 1 and --ram 1 without success....

After investigation with --cpus 20 --ram 9, 

i observe that the ram consumption is duplicated, owing to the two `samtools sort` command that are running at the same time.

i observe that the samtools snippy temporary files must have different name !!!

Snippy version: `snippy 4.3.6`

**Comment by pixuenan** [comment]
Same issue happen to me when the compute speed is not fast enough to delete the temp file of the first `samtools sort` before the second sort started.

As in the perl script `snippy`, the prefix of the temp file of the two `samtools sort` and `markdup` are all the same. The code block is as following between line `340` and `380`.

```
my $sort_temp = "-T $tmpdir/snippy.$$.";
my $sort_cpus = min($cpus, 16);
my $sort_ram = "-m ".sprintf("%dM", 1000*$ram/$sort_cpus);
$sort_cpus = "--threads $sort_cpus";
my $sortopt = "-l 0 $sort_temp $sort_cpus $sort_ram";

......
......

  # make BAM
  ($bam ? "samtools view -h -O SAM \Q$bam\E" : "bwa mem $bwaopt -t $cpus $refdir/ref.fa @reads")
    ." | samclip --max $maxsoft --ref $refdir/ref.fa.fai"
    ." | samtools sort -n $sortopt"
    ." | samtools fixmate -m - -"
    ." | samtools sort $sortopt"
    ." | samtools markdup $sort_temp -r -s - -"
    ." > $prefix.bam",
  "samtools index $prefix.bam",
```

**Comment by tseemann** [comment]
Thank you both for your good comments!

1. Yes, it seems there is a bug where the same temp prefix is being used. In my mind `$$` would be the PID of each sort command, but of course it uses the PID of the snippy process. I think `\$\$` would resolve that.  I have also learnt from https://github.com/samtools/samtools/issues/432 that I can just specify a temp dir and it will ensure unique file names.

2. You are right, because the commands are all running in a pipe, it will use the `--ram` twice. This is a bug. I am spoiled for RAM on my servers and did not hit this problem. 

I will endeavour to fix them both.

**Comment by tseemann** [comment]
These bugs were fixed by #290

**Comment by gizzlev** [comment]
Hi Tseeman, I just run 

[snippy --cpus 16 --ram 16 --reference ref.fasta --ctgs  *.fasta --outdir snippy --force](url)

Received the same error. Looks like the problem persist.

**Comment by Jiosen2** [comment]
Hi Tseemann, I had the same issue with 0 variants now
